site_name: OpenGenAI
site_url: https://llamasearchai.github.io/OpenGenAI/
repo_url: https://github.com/llamasearchai/OpenGenAI
repo_name: llamasearchai/OpenGenAI
edit_uri: ""

theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md 